### ISSUE TITLE
Uncaught error?

### ISSUE THREAD

**Issue by TheRayJohnson** [joshp23/YOURLS-AuthMgrPlus#51]
Hey,

Anyone been getting this lately? Seems to of died on me. Been working fine until today.

```
[15-Jun-2022 20:18:51 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "YOURLS_USER" in /public_html/user/plugins/authMgrPlus/plugin.php:379
Stack trace:
#0 /public_html/includes/functions-plugins.php(229): amp_get_db_stats()
#1 /public_html/includes/functions.php(187): yourls_apply_filter()
#2 /public_html/includes/functions-http.php(279): yourls_get_db_stats()
#3 /public_html/includes/functions-http.php(468): yourls_check_core_version()
#4 /public_html/includes/functions.php(1269): yourls_maybe_check_core_version()
#5 /public_html/includes/Config/Init.php(116): yourls_tell_if_new_version()
#6 /public_html/includes/load-yourls.php(26): YOURLS\Config\Init->__construct()
#7 /public_html/admin/index.php(3): require_once('/...')
#8 {main}
  thrown in /public_html/user/plugins/authMgrPlus/plugin.php on line 379

```

**Comment by DoktorJ** [comment]
I just got this today. When I upgraded to YOURLS 1.9.2 everything seemed fine, then I went to sign in today and ☠

I looked at the `plugin.php` code for the installed plugin, and found out that it's using 1.0.5??? I moved that to `plugin_old.php_1.0.5` and dropped the current version (2.3.1) in place via

```
wget "https://raw.githubusercontent.com/joshp23/YOURLS-AuthMgrPlus/master/authMgrPlus/plugin.php"
```

and all seems well now?
